### ISSUE TITLE
+1

### ISSUE THREAD

**Issue by v4hn** [Feandil/bitlbee-mattermost#1]
Nice idea. You seem to be the first one who decided to tackle it... somewhat. :)
Did this ever go further than this? What needs to be done to have "rudimentary" channel-support?

**Comment by Feandil** [comment]
Thanks :)

Unfortunately, no... After the initial motivation, I did not continue (testing is a bit painful, as I have to restart my bitlbee daemon).

There is unfortunately quite a bit missing:
- Parsing messages for channel syncing
- Support websocket (main message exchange channel)
- Encode messages and send them

**Comment by v4hn** [comment]
Too bad :-)
I would really like to have that module around to counter the general "let's use web4.0 platforms to communicate".
I'll keep in mind this exists and might get around to help it move forward :-)

**Comment by raspbeguy** [comment]
It would be so great though :)
